# Generated by Django 3.0.8 on 2021-10-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211009_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
