# Generated by Django 3.0.8 on 2021-10-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211013_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followee_user_id',
            new_name='followee_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_user_id',
            new_name='follower_user',
        ),
    ]
